name: WhatsApp CronJob

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call WhatsApp CronJob
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          https://optica-rose.vercel.app/api/cron/whatsapp
