name: WhatsApp CronJob

on:
  schedule:
    # Ejecutar a las 00:15 UTC cada día
    - cron: '15 0 * * *' # minuto(15) hora(0) día-mes(*) mes(*) día-semana(*)
  workflow_dispatch: # Permite ejecución manual

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call WhatsApp CronJob
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          https://optica-rose.vercel.app/api/cron/whatsapp
